### ISSUE TITLE
路书

### ISSUE THREAD

**Issue by xiaowanhashi** [Dafrok/BMapLib.LuShu#1]
今天跑起来这个路书对象
   handler ({map}) {
        this.mapObj = map
      },
      runLushu(){
        var lushu = new LuShu(this.mapObj,this.gpsLine,{
          autoView:true,
          icon : new BMap.Icon('../../src/assets/online.png', new BMap.Size(32,32),{anchor : new BMap.Size(27, 13)}),
          speed: 2000,
        })
        lushu.start()
      },
我点击的调用这个runlushu方法的时候确实是可以跑起来了，下面总是提示 Cannot read property 'length' of undefined
还有一个问题是如果这么定义icon的话车辆的图标会默认的显示信息窗口

**Comment by Dafrok** [comment]
问题1. 用 debugger 找到问题在哪，产生原因是什么，确定和 lib 本身有关后，整理好现象描述、输入输出、复现用例再开 issue。
问题2. 请好好看文档。

**Comment by xiaowanhashi** [comment]
你好，请问这个BmMarker组件有没有显示隐藏的方法啊？

**Comment by Dafrok** [comment]
不知道，看路书文档吧
